import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import { writeFileSync } from 'fs'
import { resolve } from 'path'

// Generates public/firebase-sw-config.js from .env so the service worker
// can access Firebase config without import.meta.env (which SW can't use).
function firebaseSwConfigPlugin() {
  return {
    name: 'firebase-sw-config',
    configResolved(config: { root: string; env: Record<string, string> }) {
      const env = loadEnv(config.env.MODE ?? 'development', config.root, '')
      const content = `// Auto-generated by vite.config.ts — do not edit manually
self.FIREBASE_CONFIG = {
  apiKey: ${JSON.stringify(env.VITE_FIREBASE_API_KEY ?? '')},
  authDomain: ${JSON.stringify(env.VITE_FIREBASE_AUTH_DOMAIN ?? '')},
  projectId: ${JSON.stringify(env.VITE_FIREBASE_PROJECT_ID ?? '')},
  messagingSenderId: ${JSON.stringify(env.VITE_FIREBASE_MESSAGING_SENDER_ID ?? '')},
  appId: ${JSON.stringify(env.VITE_FIREBASE_APP_ID ?? '')},
};
`
      writeFileSync(resolve(config.root, 'public/firebase-sw-config.js'), content)
    },
  }
}

export default defineConfig({
  plugins: [react(), firebaseSwConfigPlugin()],
  server: {
    host: true,
    port: 3000,
    proxy: {
      '/v1/api': {
        target: 'http://localhost:1500',
        changeOrigin: true,
      },
      '/socket.io': {
        target: 'http://localhost:1500',
        ws: true,
        changeOrigin: true,
      },
    },
  },
})
